// Generated by gencpp from file ahra/EmergencyResponse.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_EMERGENCYRESPONSE_H
#define AHRA_MESSAGE_EMERGENCYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ahra
{
template <class ContainerAllocator>
struct EmergencyResponse_
{
  typedef EmergencyResponse_<ContainerAllocator> Type;

  EmergencyResponse_()
    : emergency(false)  {
    }
  EmergencyResponse_(const ContainerAllocator& _alloc)
    : emergency(false)  {
  (void)_alloc;
    }



   typedef uint8_t _emergency_type;
  _emergency_type emergency;





  typedef boost::shared_ptr< ::ahra::EmergencyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ahra::EmergencyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EmergencyResponse_

typedef ::ahra::EmergencyResponse_<std::allocator<void> > EmergencyResponse;

typedef boost::shared_ptr< ::ahra::EmergencyResponse > EmergencyResponsePtr;
typedef boost::shared_ptr< ::ahra::EmergencyResponse const> EmergencyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ahra::EmergencyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ahra::EmergencyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ahra::EmergencyResponse_<ContainerAllocator1> & lhs, const ::ahra::EmergencyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.emergency == rhs.emergency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ahra::EmergencyResponse_<ContainerAllocator1> & lhs, const ::ahra::EmergencyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ahra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ahra::EmergencyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ahra::EmergencyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::EmergencyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::EmergencyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::EmergencyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::EmergencyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ahra::EmergencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa208417948d3e0ac7bed355db544b81";
  }

  static const char* value(const ::ahra::EmergencyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa208417948d3e0aULL;
  static const uint64_t static_value2 = 0xc7bed355db544b81ULL;
};

template<class ContainerAllocator>
struct DataType< ::ahra::EmergencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ahra/EmergencyResponse";
  }

  static const char* value(const ::ahra::EmergencyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ahra::EmergencyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool emergency\n"
;
  }

  static const char* value(const ::ahra::EmergencyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ahra::EmergencyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emergency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EmergencyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ahra::EmergencyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ahra::EmergencyResponse_<ContainerAllocator>& v)
  {
    s << indent << "emergency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AHRA_MESSAGE_EMERGENCYRESPONSE_H
