// Generated by gencpp from file ahra/RL_NeckAngle.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_RL_NECKANGLE_H
#define AHRA_MESSAGE_RL_NECKANGLE_H

#include <ros/service_traits.h>


#include <ahra/RL_NeckAngleRequest.h>
#include <ahra/RL_NeckAngleResponse.h>


namespace ahra
{

struct RL_NeckAngle
{

typedef RL_NeckAngleRequest Request;
typedef RL_NeckAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RL_NeckAngle
} // namespace ahra


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ahra::RL_NeckAngle > {
  static const char* value()
  {
    return "53641ec2b7d57c4826404748be4e88f1";
  }

  static const char* value(const ::ahra::RL_NeckAngle&) { return value(); }
};

template<>
struct DataType< ::ahra::RL_NeckAngle > {
  static const char* value()
  {
    return "ahra/RL_NeckAngle";
  }

  static const char* value(const ::ahra::RL_NeckAngle&) { return value(); }
};


// service_traits::MD5Sum< ::ahra::RL_NeckAngleRequest> should match
// service_traits::MD5Sum< ::ahra::RL_NeckAngle >
template<>
struct MD5Sum< ::ahra::RL_NeckAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::RL_NeckAngle >::value();
  }
  static const char* value(const ::ahra::RL_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::RL_NeckAngleRequest> should match
// service_traits::DataType< ::ahra::RL_NeckAngle >
template<>
struct DataType< ::ahra::RL_NeckAngleRequest>
{
  static const char* value()
  {
    return DataType< ::ahra::RL_NeckAngle >::value();
  }
  static const char* value(const ::ahra::RL_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ahra::RL_NeckAngleResponse> should match
// service_traits::MD5Sum< ::ahra::RL_NeckAngle >
template<>
struct MD5Sum< ::ahra::RL_NeckAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::RL_NeckAngle >::value();
  }
  static const char* value(const ::ahra::RL_NeckAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::RL_NeckAngleResponse> should match
// service_traits::DataType< ::ahra::RL_NeckAngle >
template<>
struct DataType< ::ahra::RL_NeckAngleResponse>
{
  static const char* value()
  {
    return DataType< ::ahra::RL_NeckAngle >::value();
  }
  static const char* value(const ::ahra::RL_NeckAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AHRA_MESSAGE_RL_NECKANGLE_H
