// Generated by gencpp from file ahra/Select_MotionResponse.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_SELECT_MOTIONRESPONSE_H
#define AHRA_MESSAGE_SELECT_MOTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ahra
{
template <class ContainerAllocator>
struct Select_MotionResponse_
{
  typedef Select_MotionResponse_<ContainerAllocator> Type;

  Select_MotionResponse_()
    : select_motion(0)
    , distance(0.0)  {
    }
  Select_MotionResponse_(const ContainerAllocator& _alloc)
    : select_motion(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _select_motion_type;
  _select_motion_type select_motion;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::ahra::Select_MotionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ahra::Select_MotionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Select_MotionResponse_

typedef ::ahra::Select_MotionResponse_<std::allocator<void> > Select_MotionResponse;

typedef boost::shared_ptr< ::ahra::Select_MotionResponse > Select_MotionResponsePtr;
typedef boost::shared_ptr< ::ahra::Select_MotionResponse const> Select_MotionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ahra::Select_MotionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ahra::Select_MotionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ahra::Select_MotionResponse_<ContainerAllocator1> & lhs, const ::ahra::Select_MotionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.select_motion == rhs.select_motion &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ahra::Select_MotionResponse_<ContainerAllocator1> & lhs, const ::ahra::Select_MotionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ahra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ahra::Select_MotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ahra::Select_MotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::Select_MotionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::Select_MotionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::Select_MotionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::Select_MotionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ahra::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8cc24820dfb2ba90d0f15d2ed14e6cfb";
  }

  static const char* value(const ::ahra::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8cc24820dfb2ba90ULL;
  static const uint64_t static_value2 = 0xd0f15d2ed14e6cfbULL;
};

template<class ContainerAllocator>
struct DataType< ::ahra::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ahra/Select_MotionResponse";
  }

  static const char* value(const ::ahra::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ahra::Select_MotionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 select_motion\n"
"float64 distance\n"
;
  }

  static const char* value(const ::ahra::Select_MotionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ahra::Select_MotionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.select_motion);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Select_MotionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ahra::Select_MotionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ahra::Select_MotionResponse_<ContainerAllocator>& v)
  {
    s << indent << "select_motion: ";
    Printer<int8_t>::stream(s, indent + "  ", v.select_motion);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AHRA_MESSAGE_SELECT_MOTIONRESPONSE_H
