// Generated by gencpp from file ahra/Select_MotionRequest.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_SELECT_MOTIONREQUEST_H
#define AHRA_MESSAGE_SELECT_MOTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ahra
{
template <class ContainerAllocator>
struct Select_MotionRequest_
{
  typedef Select_MotionRequest_<ContainerAllocator> Type;

  Select_MotionRequest_()
    : finish(false)  {
    }
  Select_MotionRequest_(const ContainerAllocator& _alloc)
    : finish(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finish_type;
  _finish_type finish;





  typedef boost::shared_ptr< ::ahra::Select_MotionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ahra::Select_MotionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Select_MotionRequest_

typedef ::ahra::Select_MotionRequest_<std::allocator<void> > Select_MotionRequest;

typedef boost::shared_ptr< ::ahra::Select_MotionRequest > Select_MotionRequestPtr;
typedef boost::shared_ptr< ::ahra::Select_MotionRequest const> Select_MotionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ahra::Select_MotionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ahra::Select_MotionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ahra::Select_MotionRequest_<ContainerAllocator1> & lhs, const ::ahra::Select_MotionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.finish == rhs.finish;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ahra::Select_MotionRequest_<ContainerAllocator1> & lhs, const ::ahra::Select_MotionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ahra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ahra::Select_MotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ahra::Select_MotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::Select_MotionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::Select_MotionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::Select_MotionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::Select_MotionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ahra::Select_MotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "474a58dbb494a45bb1ca99544cd64e45";
  }

  static const char* value(const ::ahra::Select_MotionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x474a58dbb494a45bULL;
  static const uint64_t static_value2 = 0xb1ca99544cd64e45ULL;
};

template<class ContainerAllocator>
struct DataType< ::ahra::Select_MotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ahra/Select_MotionRequest";
  }

  static const char* value(const ::ahra::Select_MotionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ahra::Select_MotionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finish\n"
;
  }

  static const char* value(const ::ahra::Select_MotionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ahra::Select_MotionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finish);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Select_MotionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ahra::Select_MotionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ahra::Select_MotionRequest_<ContainerAllocator>& v)
  {
    s << indent << "finish: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finish);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AHRA_MESSAGE_SELECT_MOTIONREQUEST_H
