// Generated by gencpp from file ahra/Select_Motion.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_SELECT_MOTION_H
#define AHRA_MESSAGE_SELECT_MOTION_H

#include <ros/service_traits.h>


#include <ahra/Select_MotionRequest.h>
#include <ahra/Select_MotionResponse.h>


namespace ahra
{

struct Select_Motion
{

typedef Select_MotionRequest Request;
typedef Select_MotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Select_Motion
} // namespace ahra


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ahra::Select_Motion > {
  static const char* value()
  {
    return "d51f1f90cb25facd79c884f5f7a758e6";
  }

  static const char* value(const ::ahra::Select_Motion&) { return value(); }
};

template<>
struct DataType< ::ahra::Select_Motion > {
  static const char* value()
  {
    return "ahra/Select_Motion";
  }

  static const char* value(const ::ahra::Select_Motion&) { return value(); }
};


// service_traits::MD5Sum< ::ahra::Select_MotionRequest> should match
// service_traits::MD5Sum< ::ahra::Select_Motion >
template<>
struct MD5Sum< ::ahra::Select_MotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::Select_Motion >::value();
  }
  static const char* value(const ::ahra::Select_MotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::Select_MotionRequest> should match
// service_traits::DataType< ::ahra::Select_Motion >
template<>
struct DataType< ::ahra::Select_MotionRequest>
{
  static const char* value()
  {
    return DataType< ::ahra::Select_Motion >::value();
  }
  static const char* value(const ::ahra::Select_MotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ahra::Select_MotionResponse> should match
// service_traits::MD5Sum< ::ahra::Select_Motion >
template<>
struct MD5Sum< ::ahra::Select_MotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::Select_Motion >::value();
  }
  static const char* value(const ::ahra::Select_MotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::Select_MotionResponse> should match
// service_traits::DataType< ::ahra::Select_Motion >
template<>
struct DataType< ::ahra::Select_MotionResponse>
{
  static const char* value()
  {
    return DataType< ::ahra::Select_Motion >::value();
  }
  static const char* value(const ::ahra::Select_MotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AHRA_MESSAGE_SELECT_MOTION_H
