// Generated by gencpp from file ahra/Turn_Angle.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_TURN_ANGLE_H
#define AHRA_MESSAGE_TURN_ANGLE_H

#include <ros/service_traits.h>


#include <ahra/Turn_AngleRequest.h>
#include <ahra/Turn_AngleResponse.h>


namespace ahra
{

struct Turn_Angle
{

typedef Turn_AngleRequest Request;
typedef Turn_AngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Turn_Angle
} // namespace ahra


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ahra::Turn_Angle > {
  static const char* value()
  {
    return "2d06fbbfad695cc7cf264315ed9bddd9";
  }

  static const char* value(const ::ahra::Turn_Angle&) { return value(); }
};

template<>
struct DataType< ::ahra::Turn_Angle > {
  static const char* value()
  {
    return "ahra/Turn_Angle";
  }

  static const char* value(const ::ahra::Turn_Angle&) { return value(); }
};


// service_traits::MD5Sum< ::ahra::Turn_AngleRequest> should match
// service_traits::MD5Sum< ::ahra::Turn_Angle >
template<>
struct MD5Sum< ::ahra::Turn_AngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::Turn_Angle >::value();
  }
  static const char* value(const ::ahra::Turn_AngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::Turn_AngleRequest> should match
// service_traits::DataType< ::ahra::Turn_Angle >
template<>
struct DataType< ::ahra::Turn_AngleRequest>
{
  static const char* value()
  {
    return DataType< ::ahra::Turn_Angle >::value();
  }
  static const char* value(const ::ahra::Turn_AngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ahra::Turn_AngleResponse> should match
// service_traits::MD5Sum< ::ahra::Turn_Angle >
template<>
struct MD5Sum< ::ahra::Turn_AngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::Turn_Angle >::value();
  }
  static const char* value(const ::ahra::Turn_AngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::Turn_AngleResponse> should match
// service_traits::DataType< ::ahra::Turn_Angle >
template<>
struct DataType< ::ahra::Turn_AngleResponse>
{
  static const char* value()
  {
    return DataType< ::ahra::Turn_Angle >::value();
  }
  static const char* value(const ::ahra::Turn_AngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AHRA_MESSAGE_TURN_ANGLE_H
