// Generated by gencpp from file ahra/UD_NeckAngleResponse.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_UD_NECKANGLERESPONSE_H
#define AHRA_MESSAGE_UD_NECKANGLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ahra
{
template <class ContainerAllocator>
struct UD_NeckAngleResponse_
{
  typedef UD_NeckAngleResponse_<ContainerAllocator> Type;

  UD_NeckAngleResponse_()
    : ud_neckangle(0.0)  {
    }
  UD_NeckAngleResponse_(const ContainerAllocator& _alloc)
    : ud_neckangle(0.0)  {
  (void)_alloc;
    }



   typedef double _ud_neckangle_type;
  _ud_neckangle_type ud_neckangle;





  typedef boost::shared_ptr< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UD_NeckAngleResponse_

typedef ::ahra::UD_NeckAngleResponse_<std::allocator<void> > UD_NeckAngleResponse;

typedef boost::shared_ptr< ::ahra::UD_NeckAngleResponse > UD_NeckAngleResponsePtr;
typedef boost::shared_ptr< ::ahra::UD_NeckAngleResponse const> UD_NeckAngleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ahra::UD_NeckAngleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ahra::UD_NeckAngleResponse_<ContainerAllocator1> & lhs, const ::ahra::UD_NeckAngleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ud_neckangle == rhs.ud_neckangle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ahra::UD_NeckAngleResponse_<ContainerAllocator1> & lhs, const ::ahra::UD_NeckAngleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ahra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "313e6cd6c4903c731de0626857377bb2";
  }

  static const char* value(const ::ahra::UD_NeckAngleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x313e6cd6c4903c73ULL;
  static const uint64_t static_value2 = 0x1de0626857377bb2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ahra/UD_NeckAngleResponse";
  }

  static const char* value(const ::ahra::UD_NeckAngleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ud_neckangle\n"
;
  }

  static const char* value(const ::ahra::UD_NeckAngleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ud_neckangle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UD_NeckAngleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ahra::UD_NeckAngleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ahra::UD_NeckAngleResponse_<ContainerAllocator>& v)
  {
    s << indent << "ud_neckangle: ";
    Printer<double>::stream(s, indent + "  ", v.ud_neckangle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AHRA_MESSAGE_UD_NECKANGLERESPONSE_H
