// Generated by gencpp from file ahra/UD_NeckAngle.msg
// DO NOT EDIT!


#ifndef AHRA_MESSAGE_UD_NECKANGLE_H
#define AHRA_MESSAGE_UD_NECKANGLE_H

#include <ros/service_traits.h>


#include <ahra/UD_NeckAngleRequest.h>
#include <ahra/UD_NeckAngleResponse.h>


namespace ahra
{

struct UD_NeckAngle
{

typedef UD_NeckAngleRequest Request;
typedef UD_NeckAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UD_NeckAngle
} // namespace ahra


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ahra::UD_NeckAngle > {
  static const char* value()
  {
    return "54d0093350d66ae9f81f65f132656855";
  }

  static const char* value(const ::ahra::UD_NeckAngle&) { return value(); }
};

template<>
struct DataType< ::ahra::UD_NeckAngle > {
  static const char* value()
  {
    return "ahra/UD_NeckAngle";
  }

  static const char* value(const ::ahra::UD_NeckAngle&) { return value(); }
};


// service_traits::MD5Sum< ::ahra::UD_NeckAngleRequest> should match
// service_traits::MD5Sum< ::ahra::UD_NeckAngle >
template<>
struct MD5Sum< ::ahra::UD_NeckAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::UD_NeckAngle >::value();
  }
  static const char* value(const ::ahra::UD_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::UD_NeckAngleRequest> should match
// service_traits::DataType< ::ahra::UD_NeckAngle >
template<>
struct DataType< ::ahra::UD_NeckAngleRequest>
{
  static const char* value()
  {
    return DataType< ::ahra::UD_NeckAngle >::value();
  }
  static const char* value(const ::ahra::UD_NeckAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ahra::UD_NeckAngleResponse> should match
// service_traits::MD5Sum< ::ahra::UD_NeckAngle >
template<>
struct MD5Sum< ::ahra::UD_NeckAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ahra::UD_NeckAngle >::value();
  }
  static const char* value(const ::ahra::UD_NeckAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ahra::UD_NeckAngleResponse> should match
// service_traits::DataType< ::ahra::UD_NeckAngle >
template<>
struct DataType< ::ahra::UD_NeckAngleResponse>
{
  static const char* value()
  {
    return DataType< ::ahra::UD_NeckAngle >::value();
  }
  static const char* value(const ::ahra::UD_NeckAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AHRA_MESSAGE_UD_NECKANGLE_H
