(cl:in-package ahra-srv)
(cl:export '(SM_FINISH-VAL
          SM_FINISH
          TA_FINISH-VAL
          TA_FINISH
          UD_FINISH-VAL
          UD_FINISH
          RL_FINISH-VAL
          RL_FINISH
          EM_FINISH-VAL
          EM_FINISH
          ST_FINISH-VAL
          ST_FINISH
          WALKCOUNT-VAL
          WALKCOUNT
          REQUEST_ID-VAL
          REQUEST_ID
          SELECT_MOTION-VAL
          SELECT_MOTION
          DISTANCE-VAL
          DISTANCE
          TURN_ANGLE-VAL
          TURN_ANGLE
          UD_NECKANGLE-VAL
          UD_NECKANGLE
          RL_NECKANGLE-VAL
          RL_NECKANGLE
          EMERGENCY-VAL
          EMERGENCY
          SUCCESS-VAL
          SUCCESS
))